name: Build and Push Frontend Image

on:
  push:
    branches:
      - deploy

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Frontend Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-innovatech:latest .

      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend-innovatech:latest